const Classrooms_info =
    {
        "SEDE_CENTRALE": {
            "1": {
                "_id": "1",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "362",
                "_superficie": "318",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE D001"
            },
            "2": {
                "_id": "2",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "332",
                "_superficie": "294",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE E002"
            },
            "3": {
                "_id": "3",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "352",
                "_superficie": "316",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE D003"
            },
            "4": {
                "_id": "4",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "326",
                "_superficie": "285",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE E004"
            },
            "5": {
                "_id": "5",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "362",
                "_superficie": "319",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE D005"
            },
            "6": {
                "_id": "6",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "302",
                "_superficie": "254",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE E006"
            },
            "7": {
                "_id": "7",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "148",
                "_superficie": "132",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XPTE R001"
            },
            "8": {
                "_id": "8",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "278",
                "_superficie": "214",
                "_fabbricato": "Area Nord",
                "_id_locale": "TO_CEN04 XPTE E001"
            },
            "10": {
                "_id": "10",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "140",
                "_superficie": "145",
                "_fabbricato": "Area Nord",
                "_id_locale": "TO_CEN04 XPTE H001"
            },
            "11": {
                "_id": "11",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "101",
                "_superficie": "98",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XPTE Q009"
            },
            "12": {
                "_id": "12",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "285",
                "_superficie": "256",
                "_fabbricato": "Area Nord",
                "_id_locale": "TO_CEN04 XPTE M009"
            },
            "13": {
                "_id": "13",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "100",
                "_superficie": "95",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XPTE Q008"
            },
            "14": {
                "_id": "14",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "178",
                "_superficie": "175",
                "_fabbricato": "Area Nord",
                "_id_locale": "TO_CEN04 XS01 M008"
            },
            "15": {
                "_id": "15",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "98",
                "_superficie": "88",
                "_fabbricato": "Area Sud - Parte 1",
                "_id_locale": "TO_CEN01 XPTE E020"
            },
            "16": {
                "_id": "16",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "195",
                "_superficie": "191",
                "_fabbricato": "Area Nord",
                "_id_locale": "TO_CEN04 XPTE M011"
            },
            "17": {
                "_id": "17",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "32",
                "_superficie": "68",
                "_fabbricato": "Area Sud - Parte 1",
                "_id_locale": "TO_CEN01 XPTE D002"
            },
            "19": {
                "_id": "19",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "32",
                "_superficie": "69",
                "_fabbricato": "Area Sud - Parte 1",
                "_id_locale": "TO_CEN01 XPTE D001"
            },
            "27": {
                "_id": "27",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "221",
                "_superficie": "196",
                "_fabbricato": "Ex centrale termica",
                "_id_locale": "TO_CEN05 XPTE B056"
            },
            "29": {
                "_id": "29",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "213",
                "_superficie": "183",
                "_fabbricato": "Ex centrale termica",
                "_id_locale": "TO_CEN05 XPTE B055"
            },
            "10A": {
                "_id": "10A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "252",
                "_superficie": "265",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE F004"
            },
            "10C": {
                "_id": "10C",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Secondo Piano",
                "_capienza": "118",
                "_superficie": "119",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP02 Q014"
            },
            "10D": {
                "_id": "10D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "127",
                "_superficie": "131",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 Q001"
            },
            "10I": {
                "_id": "10I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "88",
                "_superficie": "111",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 011"
            },
            "11B": {
                "_id": "11B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "47",
                "_superficie": "60",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XP01 Q006"
            },
            "11I": {
                "_id": "11I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "96",
                "_superficie": "167",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 012"
            },
            "11S": {
                "_id": "11S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "72",
                "_superficie": "78",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 D014"
            },
            "11T": {
                "_id": "11T",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "142",
                "_superficie": "132",
                "_fabbricato": "Ex Tornerie",
                "_id_locale": "TO_CIT09 XPTE 137"
            },
            "12A": {
                "_id": "12A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "252",
                "_superficie": "259",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE F003"
            },
            "12D": {
                "_id": "12D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "117",
                "_superficie": "119",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 Q009"
            },
            "12I": {
                "_id": "12I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "80",
                "_superficie": "185",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 013"
            },
            "13A": {
                "_id": "13A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "51",
                "_superficie": "64",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE C004"
            },
            "13B": {
                "_id": "13B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "51",
                "_superficie": "82",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XP01 Q005"
            },
            "13S": {
                "_id": "13S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "119",
                "_superficie": "133",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 C016"
            },
            "15A": {
                "_id": "15A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "97",
                "_superficie": "110",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE C008"
            },
            "17A": {
                "_id": "17A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "96",
                "_superficie": "102",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE C007"
            },
            "19A": {
                "_id": "19A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "87",
                "_superficie": "84",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE C003"
            },
            "1B": {
                "_id": "1B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "196",
                "_superficie": "240",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP01 L005"
            },
            "1D": {
                "_id": "1D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "89",
                "_superficie": "102",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 G009"
            },
            "1I": {
                "_id": "1I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "149",
                "_superficie": "176",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 002"
            },
            "1M": {
                "_id": "1M",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "76",
                "_superficie": "139",
                "_fabbricato": "Aule M",
                "_id_locale": "TO_CIT02 XPTE 007"
            },
            "1P": {
                "_id": "1P",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "220",
                "_superficie": "217",
                "_fabbricato": "Aule P, nuovi fabbricati",
                "_id_locale": "TO_CIT22 XPTE 036"
            },
            "1S": {
                "_id": "1S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "156",
                "_superficie": "163",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 D005"
            },
            "1T": {
                "_id": "1T",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "90",
                "_superficie": "102",
                "_fabbricato": "Ex Tornerie",
                "_id_locale": "TO_CIT09 XPTE 057"
            },
            "21A": {
                "_id": "21A",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Terra",
                "_capienza": "47",
                "_superficie": "67",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XPTE C001"
            },
            "27B": {
                "_id": "27B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "221",
                "_superficie": "202",
                "_fabbricato": "Ex centrale termica",
                "_id_locale": "TO_CEN05 XP01 B029"
            },
            "29B": {
                "_id": "29B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "213",
                "_superficie": "183",
                "_fabbricato": "Ex centrale termica",
                "_id_locale": "TO_CEN05 XP01 B031"
            },
            "2C": {
                "_id": "2C",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Secondo Piano",
                "_capienza": "121",
                "_superficie": "125",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP02 Q001"
            },
            "2D": {
                "_id": "2D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "123",
                "_superficie": "122",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 Q005"
            },
            "2I": {
                "_id": "2I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "87",
                "_superficie": "109",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 003"
            },
            "2M": {
                "_id": "2M",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "144",
                "_superficie": "134",
                "_fabbricato": "Aule M",
                "_id_locale": "TO_CIT02 XPTE 011"
            },
            "2N": {
                "_id": "2N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "139",
                "_superficie": "138",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XPTE 005"
            },
            "2P": {
                "_id": "2P",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "220",
                "_superficie": "218",
                "_fabbricato": "Aule P, nuovi fabbricati",
                "_id_locale": "TO_CIT22 XPTE 038"
            },
            "2T": {
                "_id": "2T",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "120",
                "_superficie": "142",
                "_fabbricato": "Ex Tornerie",
                "_id_locale": "TO_CIT09 XPTE 040"
            },
            "3I": {
                "_id": "3I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "148",
                "_superficie": "173",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 004"
            },
            "3M": {
                "_id": "3M",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "128",
                "_superficie": "144",
                "_fabbricato": "Aule M",
                "_id_locale": "TO_CIT02 XPTE 027"
            },
            "3N": {
                "_id": "3N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "130",
                "_superficie": "143",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XPTE 006"
            },
            "3P": {
                "_id": "3P",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "220",
                "_superficie": "218",
                "_fabbricato": "Aule P, nuovi fabbricati",
                "_id_locale": "TO_CIT22 XPTE 015"
            },
            "3S": {
                "_id": "3S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "156",
                "_superficie": "163",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 D007"
            },
            "4C": {
                "_id": "4C",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Secondo Piano",
                "_capienza": "120",
                "_superficie": "130",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP02 Q011"
            },
            "4D": {
                "_id": "4D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "121",
                "_superficie": "131",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 Q010"
            },
            "4I": {
                "_id": "4I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "96",
                "_superficie": "171",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 005"
            },
            "4M": {
                "_id": "4M",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "60",
                "_superficie": "65",
                "_fabbricato": "Aule M",
                "_id_locale": "TO_CIT02 XPTE 016"
            },
            "4N": {
                "_id": "4N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "135",
                "_superficie": "133",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XPTE 007"
            },
            "4P": {
                "_id": "4P",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "220",
                "_superficie": "216",
                "_fabbricato": "Aule P, nuovi fabbricati",
                "_id_locale": "TO_CIT22 XPTE 005"
            },
            "4T": {
                "_id": "4T",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "130",
                "_superficie": "144",
                "_fabbricato": "Ex Tornerie",
                "_id_locale": "TO_CIT09 XPTE 113"
            },
            "5B": {
                "_id": "5B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "51",
                "_superficie": "52",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XP01 Q010"
            },
            "5I": {
                "_id": "5I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "138",
                "_superficie": "162",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 006"
            },
            "5M": {
                "_id": "5M",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "76",
                "_superficie": "143",
                "_fabbricato": "Aule M",
                "_id_locale": "TO_CIT02 XPTE 030"
            },
            "5N": {
                "_id": "5N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "68",
                "_superficie": "69",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XPTE 013"
            },
            "5S": {
                "_id": "5S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "156",
                "_superficie": "163",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 D009"
            },
            "6C": {
                "_id": "6C",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Secondo Piano",
                "_capienza": "25",
                "_superficie": "80",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP02 Q002"
            },
            "6D": {
                "_id": "6D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "25",
                "_superficie": "71",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 Q004"
            },
            "6I": {
                "_id": "6I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "48",
                "_superficie": "128",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 007"
            },
            "6N": {
                "_id": "6N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "139",
                "_superficie": "137",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XPTE 017"
            },
            "7B": {
                "_id": "7B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "97",
                "_superficie": "101",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XP01 Q009"
            },
            "7D": {
                "_id": "7D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "78",
                "_superficie": "83",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 G008"
            },
            "7I": {
                "_id": "7I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "140",
                "_superficie": "162",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 008"
            },
            "7N": {
                "_id": "7N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "112",
                "_superficie": "146",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XPTE 015"
            },
            "7S": {
                "_id": "7S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "156",
                "_superficie": "163",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 D011"
            },
            "7T": {
                "_id": "7T",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "144",
                "_superficie": "132",
                "_fabbricato": "Ex Tornerie",
                "_id_locale": "TO_CIT09 XPTE 090"
            },
            "8C": {
                "_id": "8C",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Secondo Piano",
                "_capienza": "193",
                "_superficie": "223",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP02 Q007"
            },
            "8D": {
                "_id": "8D",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Terzo Piano",
                "_capienza": "93",
                "_superficie": "107",
                "_fabbricato": "Area Centrale",
                "_id_locale": "TO_CEN03 XP03 Q003"
            },
            "8I": {
                "_id": "8I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "97",
                "_superficie": "128",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 009"
            },
            "8N": {
                "_id": "8N",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Primo Piano",
                "_capienza": "64",
                "_superficie": "119",
                "_fabbricato": "Ex Stampati",
                "_id_locale": "TO_CIT03 XP01 013"
            },
            "9B": {
                "_id": "9B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Primo Piano",
                "_capienza": "47",
                "_superficie": "61",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XP01 Q008"
            },
            "9I": {
                "_id": "9I",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Interrato",
                "_capienza": "107",
                "_superficie": "135",
                "_fabbricato": "Corte Interrata",
                "_id_locale": "TO_CIT08 XS01 010"
            },
            "9S": {
                "_id": "9S",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Corso Duca degli Abruzzi",
                "_piano": "Piano Interrato",
                "_capienza": "72",
                "_superficie": "83",
                "_fabbricato": "Area Sud - Parte 2",
                "_id_locale": "TO_CEN02 XS01 D013"
            },
            "9T": {
                "_id": "9T",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "144",
                "_superficie": "132",
                "_fabbricato": "Ex Tornerie",
                "_id_locale": "TO_CIT09 XPTE 092"
            },
            "R1": {
                "_id": "R1",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "300",
                "_superficie": "119",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XPTE 001"
            },
            "R1B": {
                "_id": "R1B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Primo Piano",
                "_capienza": "150",
                "_superficie": "141",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XP01 006"
            },
            "R2": {
                "_id": "R2",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "300",
                "_superficie": "119",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XPTE 002"
            },
            "R2B": {
                "_id": "R2B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Primo Piano",
                "_capienza": "150",
                "_superficie": "141",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XP01 007"
            },
            "R3": {
                "_id": "R3",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "300",
                "_superficie": "119",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XPTE 003"
            },
            "R3B": {
                "_id": "R3B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Primo Piano",
                "_capienza": "150",
                "_superficie": "141",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XP01 005"
            },
            "R4": {
                "_id": "R4",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Piano Terra",
                "_capienza": "300",
                "_superficie": "120",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XPTE 004"
            },
            "R4B": {
                "_id": "R4B",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Sede Centrale - Cittadella Politecnica",
                "_piano": "Primo Piano",
                "_capienza": "150",
                "_superficie": "141",
                "_fabbricato": "Aule R",
                "_id_locale": "TO_CIT06 XP01 008"
            }
        },
        "MIRAFIORI": {
            "01AM": {
                "_id": "01AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "93",
                "_superficie": "158.53",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE C008"
            },
            "02AM": {
                "_id": "02AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "99",
                "_superficie": "158.53",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE C002"
            },
            "03AM": {
                "_id": "03AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "32",
                "_superficie": "128.27",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE C003"
            },
            "04AM": {
                "_id": "04AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "199",
                "_superficie": "188.78",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE C004"
            },
            "05AM": {
                "_id": "05AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "49",
                "_superficie": "72.23",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE E005"
            },
            "06AM": {
                "_id": "06AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "61",
                "_superficie": "72.21",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE E006"
            },
            "07AM": {
                "_id": "07AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Piano Terra",
                "_capienza": "49",
                "_superficie": "74.38",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XPTE E007"
            },
            "11AM": {
                "_id": "11AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Primo Piano",
                "_capienza": "99",
                "_superficie": "158.53",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XP01 C001"
            },
            "12AM": {
                "_id": "12AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Primo Piano",
                "_capienza": "99",
                "_superficie": "158.53",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XP01 C002"
            },
            "13AM": {
                "_id": "13AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Primo Piano",
                "_capienza": "99",
                "_superficie": "128.27",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XP01 C003"
            },
            "14AM": {
                "_id": "14AM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Mirafiori",
                "_piano": "Primo Piano",
                "_capienza": "133",
                "_superficie": "188.22",
                "_fabbricato": "Mirafiori",
                "_id_locale": "TO_MIR01 XP01 C004"
            }
        },
        "VALENTINO": {
            "1V": {
                "_id": "1V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Secondo Piano",
                "_capienza": "140",
                "_superficie": "160.34",
                "_fabbricato": "Laboratori",
                "_id_locale": " TO_CAS06 XP02 S003"
            },
            "2V": {
                "_id": "2V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Terra",
                "_capienza": "100",
                "_superficie": "136.55",
                "_fabbricato": "Laboratori",
                "_id_locale": " TO_CAS06 XPTE S004"
            },
            "3V": {
                "_id": "3V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Terra",
                "_capienza": "56",
                "_superficie": "136.25",
                "_fabbricato": "Ala Nord",
                "_id_locale": " TO_CAS02 XPTE F003"
            },
            "4V": {
                "_id": "4V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Terra",
                "_capienza": "80",
                "_superficie": "137.19",
                "_fabbricato": "Ala Sud",
                "_id_locale": " TO_CAS03 XPTE E002"
            },
            "5V": {
                "_id": "5V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Terra",
                "_capienza": "56",
                "_superficie": "138.37",
                "_fabbricato": "Ala Nord",
                "_id_locale": " TO_CAS02 XPTE F005"
            },
            "6V": {
                "_id": "6V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Terra",
                "_capienza": "80",
                "_superficie": "138.76",
                "_fabbricato": "Ala Sud",
                "_id_locale": " TO_CAS03 XPTE E003"
            },
            "7V": {
                "_id": "7V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Terra",
                "_capienza": "100",
                "_superficie": "106.74",
                "_fabbricato": "Manica Chevalley",
                "_id_locale": " TO_CAS04 XPTE L010"
            },
            "8V": {
                "_id": "8V",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Castello del Valentino",
                "_piano": "Piano Interrato",
                "_capienza": "72",
                "_superficie": "147.61",
                "_fabbricato": "Manica Nuova",
                "_id_locale": " TO_CAS07 XS01 T009"
            },
            "2VM": {
                "_id": "2VM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Via Morgari",
                "_piano": "Piano Terra",
                "_capienza": "90",
                "_superficie": "103.81",
                "_fabbricato": "Morgari",
                "_id_locale": " TO_MOR01 XPTE 001"
            },
            "3VM": {
                "_id": "3VM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Via Morgari",
                "_piano": "Piano Terra",
                "_capienza": "24",
                "_superficie": "68.09",
                "_fabbricato": "Morgari",
                "_id_locale": " TO_MOR01 XPTE 014"
            },
            "4VM": {
                "_id": "4VM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Via Morgari",
                "_piano": "Primo Piano",
                "_capienza": "56",
                "_superficie": "135.39",
                "_fabbricato": "Morgari",
                "_id_locale": " TO_MOR01 XP01 009"
            },
            "5VM": {
                "_id": "5VM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Via Morgari",
                "_piano": "Primo Piano",
                "_capienza": "24",
                "_superficie": "34.86",
                "_fabbricato": "Morgari",
                "_id_locale": " TO_MOR01 XP01 008"
            },
            "6VM": {
                "_id": "6VM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Via Morgari",
                "_piano": "Secondo Piano",
                "_capienza": "25",
                "_superficie": "71.66",
                "_fabbricato": "Morgari",
                "_id_locale": " TO_MOR01 XP02 016"
            },
            "7VM": {
                "_id": "7VM",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Via Morgari",
                "_piano": "Secondo Piano",
                "_capienza": "76",
                "_superficie": "260.92",
                "_fabbricato": "Morgari",
                "_id_locale": " TO_MOR01 XP02 007"
            }
        },
        "LINGOTTO": {
            "201": {
                "_id": "201",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "119",
                "_superficie": "150.85",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 004"
            },
            "202": {
                "_id": "202",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "119",
                "_superficie": "150.19",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 005"
            },
            "203": {
                "_id": "203",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "36",
                "_superficie": "74.77",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 006"
            },
            "204": {
                "_id": "204",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "30",
                "_superficie": "61.77",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 007"
            },
            "205": {
                "_id": "205",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "45",
                "_superficie": "65.55",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 017"
            },
            "206": {
                "_id": "206",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "57",
                "_superficie": "74.18",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 021"
            },
            "207": {
                "_id": "207",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "68",
                "_superficie": "171.03",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 036"
            },
            "208": {
                "_id": "208",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "62",
                "_superficie": "172.19",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 037"
            },
            "209": {
                "_id": "209",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "30",
                "_superficie": "62.37",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 030"
            },
            "210": {
                "_id": "210",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "28",
                "_superficie": "61.89",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 039"
            },
            "211": {
                "_id": "211",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "14",
                "_superficie": "61.79",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 041"
            },
            "212": {
                "_id": "212",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "28",
                "_superficie": "62.54",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 032"
            },
            "213": {
                "_id": "213",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Secondo Piano",
                "_capienza": "28",
                "_superficie": "61.74",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP02 042"
            },
            "300": {
                "_id": "300",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "60",
                "_superficie": "171.27",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 027"
            },
            "301": {
                "_id": "301",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "96",
                "_superficie": "151.10",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 005"
            },
            "302": {
                "_id": "302",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "96",
                "_superficie": "150.50",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 006"
            },
            "303": {
                "_id": "303",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "36",
                "_superficie": "74.96",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 007"
            },
            "304": {
                "_id": "304",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "64",
                "_superficie": "128.37",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 008"
            },
            "305": {
                "_id": "305",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "36",
                "_superficie": "74.95",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 022"
            },
            "306": {
                "_id": "306",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "98",
                "_superficie": "125.63",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 036"
            },
            "307": {
                "_id": "307",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "30",
                "_superficie": "126.12",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 037"
            },
            "308": {
                "_id": "308",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "16",
                "_superficie": "65.25",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 001"
            },
            "309": {
                "_id": "309",
                "_currentfasce_libere": "",
                "_fasce_libere": "0",
                "_sede": "Lingotto",
                "_piano": "Terzo Piano",
                "_capienza": "30",
                "_superficie": "61.67",
                "_fabbricato": "Lingotto",
                "_id_locale": " TO_LIN01 XP03 003"
            }
        }
    }

const Classrooms_order = {
    '_id':
        [
            '1', '3', '5', '7', '11', '13', '15', '17', '19', '27', '29', '2', '4', '6', '8', '10', '12', '14', '16', '10A', '12A', '13A', '15A', '17A', '19A', '21A', '5B', '7B', '9B', '11B', '13B', '1B', '27B', '29B', '2C', '4C', '6C', '8C', '10C', '1D', '2D', '4D', '6D', '7D', '8D', '10D', '12D', '1I', '2I', '3I', '4I', '5I', '6I', '7I', '8I', '9I', '10I', '11I', '12I', '1M', '2M', '3M', '4M', '5M', '2N', '3N', '4N', '5N', '6N', '7N', '8N', '1P', '2P', '3P', '4P', 'R1', 'R1B', 'R2', 'R2B', 'R3', 'R3B', 'R4', 'R4B', '1S', '3S', '5S', '7S', '9S', '11S', '1T', '2T', '4T', '7T', '9T', '13S', '11T',
            "01AM", "02AM", "03AM", "04AM", "05AM", "06AM", "07AM", "11AM", "12AM", "13AM", "14AM",
            "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "300", "301", "302", "303", "304", "305", "306", "307", "308", "309",
            "1V", "2V", "3V", "4V", "5V", "6V", "7V", "8V", "2VM", "3VM", "4VM", "5VM", "6VM", "7VM"
        ],
    '_fasce_libere':
        [8, 7, 6, 5, 4, 3, 2, 1, 0],
    '_sede':
        [
            'Castello del Valentino',
            'Lingotto',
            'Mirafiori',
            'Sede Centrale - Corso Duca degli Abruzzi',
            'Sede Centrale - Cittadella Politecnica',
            'Via Morgari'
        ],
    '_piano':
        [
            'Piano Terra',
            'Piano Interrato',
            'Primo Piano',
            'Secondo Piano',
            'Terzo Piano'
        ],
    '_capienza':
    [362, 352, 332, 326, 302, 300, 285, 278, 252, 221, 220, 213, 199, 196, 195, 193, 178, 156, 150, 149, 148, 144, 142, 140, 139, 138, 135, 133, 130, 128, 127, 123, 121, 120, 119, 118, 117, 112, 107, 101, 100, 99, 98, 97, 96, 93, 90, 89, 88, 87, 80, 78, 76, 72, 68, 64, 62, 61, 60, 57, 56, 51, 49, 48, 47, 45, 36, 32, 30, 28, 25, 24, 16, 14],
    '_superficie':
    [319, 318, 316, 294, 285, 265, 260.92, 259, 256, 254, 240, 223, 218, 217, 216, 214, 202, 196, 191, 188.78, 188.22, 185, 183, 176, 175, 173, 172.19, 171.27, 171.03, 171, 167, 163, 162, 160.34, 158.53, 151.1, 150.85, 150.5, 150.19, 147.61, 146, 145, 144, 143, 142, 141, 139, 138.76, 138.37, 138, 137.19, 137, 136.55, 136.25, 135.39, 135, 134, 133, 132, 131, 130, 128.37, 128.27, 128, 126.12, 125.63, 125, 122, 120, 119, 111, 110, 109, 107, 106.74, 103.81, 102, 101, 98, 95, 88, 84, 83, 82, 80, 78, 74.96, 74.95, 74.77, 74.38, 74.18, 72.23, 72.21, 71.66, 71, 69, 68.09, 68, 67, 65.55, 65.25, 65, 64, 62.54, 62.37, 61.89, 61.79, 61.77, 61.74, 61.67, 61, 60, 52, 34.86],
    '_fabbricato': [
        'Ala Nord',
        'Ala Sud',
        'Area Centrale',
        'Area Nord',
        'Area Sud - Parte 1',
        'Area Sud - Parte 2',
        'Aule M',
        'Aule P, nuovi fabbricati',
        'Aule R',
        'Corte Interrata',
        'Ex Stampati',
        'Ex Tornerie',
        'Ex centrale termica',
        'Laboratori',
        'Lingotto',
        'Manica Chevalley',
        'Manica Nuova',
        'Mirafiori',
        'Morgari']
}



